import type { Restaurant } from "./types";

function mesa(
  partial: Omit<Restaurant, "mapUrl"> & { query: string },
): Restaurant {
  const { query, website, ...rest } = partial;
  return {
    ...rest,
    website,
    mapUrl: `https://maps.google.com/?q=${encodeURIComponent(query)}`,
  };
}

/** Mesas del PDF Restaurantes Mar de Imperios. */
export function seedRestaurants(): Restaurant[] {
  return [
    mesa({
      id: "mesa_galeyan",
      name: "Galeyan",
      zone: "Estambul",
      hours: "9:00 a 00:00",
      howFar: "Planta baja del hotel",
      style:
        "Cocina de Gaziantep (UNESCO): especias, aceite de oliva, cordero y pistache.",
      reservation: "recomendado",
      website: "https://www.galeyann.com",
      query: "Galeyan Restaurant Hotel Sura Design Istanbul",
      lat: 41.0065,
      lng: 28.9784,
    }),
    mesa({
      id: "mesa_deraliye_terrace",
      name: "Deraliye Terrace",
      zone: "Estambul",
      hours: "11:30 a 00:00",
      howFar: "Quinto piso del hotel",
      style:
        "Ambiente romántico, vistas y cocina palaciega otomana.",
      reservation: "recomendado",
      website: "https://www.deraliyeterrace.com",
      query: "Deraliye Terrace Istanbul",
      lat: 41.0066,
      lng: 28.9785,
    }),
    mesa({
      id: "mesa_deraliye_ottoman",
      name: "Deraliye Ottoman Cuisine",
      zone: "Estambul",
      hours: "12:00 a 23:30",
      howFar: "Justo enfrente del hotel",
      style:
        "1 estrella Michelin. Servicio de gala, vajilla histórica y platos imperiales.",
      reservation: "recomendado",
      website: "https://www.deraliyerestaurant.com",
      query: "Deraliye Ottoman Cuisine Istanbul",
      lat: 41.0069,
      lng: 28.978,
    }),
    mesa({
      id: "mesa_aura_garden",
      name: "Aura Garden",
      zone: "Estambul",
      hours: "7:00 a 3:00",
      howFar: "Justo frente al hotel",
      style:
        "Fusión internacional, oasis urbano con vistas a Hagia Sophia.",
      reservation: "recomendado",
      website: "https://www.auragardenrestaurant.com",
      query: "Aura Garden Restaurant Istanbul",
      lat: 41.0071,
      lng: 28.9788,
    }),
    mesa({
      id: "mesa_lokanta_1741",
      name: "Lokanta 1741",
      zone: "Estambul",
      hours: "Lunes a viernes 16:00 a 00:00 · sábado y domingo 12:00 a 00:00",
      howFar: "4 min caminando",
      style:
        "Recetas antiguas con técnicas modernas, en un ambiente histórico.",
      reservation: "recomendado",
      website: "https://www.lokanta1741.com",
      query: "Lokanta 1741 Istanbul",
      lat: 41.008,
      lng: 28.9766,
    }),
    mesa({
      id: "mesa_matbah",
      name: "Matbah",
      zone: "Estambul",
      hours: "9:00 a 22:30",
      howFar: "7 min caminando",
      style:
        "Cordero, pato y ganso, sopas de almendra y pilaf, ambiente de corte otomana.",
      reservation: "indispensable",
      website: "https://www.matbahrestaurant.com",
      query: "Matbah Restaurant Istanbul",
      lat: 41.0086,
      lng: 28.9802,
    }),
    mesa({
      id: "mesa_koftecisi",
      name: "Tarihi Sultanahmet Köftecisi",
      zone: "Estambul",
      hours: "10:00 a 22:00",
      howFar: "4 min caminando",
      style: "Institución de Sultanahmet: comida sencilla y local.",
      reservation: "no_necesario",
      website: "https://www.sultanahmetkoftesi.com",
      query: "Tarihi Sultanahmet Koftecisi",
      lat: 41.0063,
      lng: 28.9768,
    }),
    mesa({
      id: "mesa_khorasani",
      name: "Khorasani",
      zone: "Estambul",
      hours: "11:00 a 2:00",
      howFar: "1 min caminando",
      style: "Carnes a la parrilla y kebab, ambiente informal.",
      reservation: "no_necesario",
      website: "https://www.khorasanikebab.com",
      query: "Khorasani Kebab Istanbul",
      lat: 41.0068,
      lng: 28.9777,
    }),
    mesa({
      id: "mesa_tugra",
      name: "Tuğra",
      zone: "Estambul",
      hours: "19:00 a 23:00",
      howFar: "Çırağan Palace Kempinski, 20 min en taxi",
      style:
        "Recetas reales de los archivos del Palacio de Topkapı.",
      reservation: "indispensable",
      reservationNote: "Antes de iniciar el viaje",
      website: "https://www.tugra.com",
      query: "Tugra Restaurant Ciragan Palace Istanbul",
      lat: 41.0454,
      lng: 29.0177,
    }),
    mesa({
      id: "mesa_turk",
      name: "TURK Fatih Tutak",
      zone: "Estambul",
      hours: "18:30 a 23:30 · cerrado lunes y domingo",
      howFar: "20 min en taxi",
      style: "2 estrellas Michelin, cocina turca moderna.",
      reservation: "indispensable",
      reservationNote: "Antes de empezar el viaje",
      query: "TURK Fatih Tutak Istanbul",
      lat: 41.0583,
      lng: 28.9817,
    }),
    mesa({
      id: "mesa_neolokal",
      name: "Neolokal",
      zone: "Estambul",
      hours: "18:00 a 1:00 · cerrado lunes y domingo",
      howFar: "15 min en taxi",
      style:
        "1 estrella Michelin y 1 estrella verde, cocina contemporánea.",
      reservation: "indispensable",
      reservationNote: "Antes de empezar el viaje",
      website: "https://www.neolokal.com",
      query: "Neolokal Istanbul",
      lat: 41.0254,
      lng: 28.9742,
    }),
    mesa({
      id: "mesa_araf",
      name: "Araf Istanbul",
      zone: "Estambul",
      hours: "19:00 a 22:00 · cerrado lunes y martes",
      howFar: "20 min en taxi",
      style: "1 estrella Michelin, cocina contemporánea al fuego.",
      reservation: "indispensable",
      reservationNote: "Antes de iniciar el viaje",
      website: "https://www.arafistanbul.com",
      query: "Araf Istanbul restaurant",
      lat: 41.0325,
      lng: 28.9748,
    }),
    mesa({
      id: "mesa_tasula",
      name: "Tasula",
      zone: "Capadocia",
      hours: "7:30 a 23:00",
      howFar: "En el hotel",
      style: "Platos tradicionales de Anatolia y menú internacional.",
      reservation: "recomendado",
      website: "https://www.seraphimcavehotel.com",
      query: "Tasula Restaurant Seraphim Cave Goreme",
      lat: 38.6428,
      lng: 34.8305,
    }),
    mesa({
      id: "mesa_revithia",
      name: "Revithia",
      zone: "Capadocia",
      hours: "18:00 a 00:00 · cierra domingo",
      howFar: "15 min en taxi",
      style: "1 estrella Michelin, alta gastronomía en Capadocia.",
      reservation: "indispensable",
      reservationNote: "Antes de iniciar el viaje",
      website: "https://www.revithia.com",
      query: "Revithia Restaurant Cappadocia",
      lat: 38.6314,
      lng: 34.9117,
    }),
    mesa({
      id: "mesa_babayan",
      name: "Babayan Evi",
      zone: "Capadocia",
      hours: "8:00 a 00:00",
      howFar: "25 min en taxi",
      style: "Estrella Michelin verde, productos de Capadocia.",
      reservation: "indispensable",
      website: "https://www.babayanevi.com",
      query: "Babayan Evi Mustafapasa",
      lat: 38.5847,
      lng: 34.8956,
    }),
    mesa({
      id: "mesa_gorgoli",
      name: "Gorgoli",
      zone: "Capadocia",
      hours: "9:00 a 22:00",
      howFar: "5 min caminando",
      style: "Cocina anatolia contemporánea y tradicional.",
      reservation: "recomendado",
      website: "https://mysimpleerb.com",
      query: "Gorgoli Restaurant Goreme",
      lat: 38.6436,
      lng: 34.829,
    }),
    mesa({
      id: "mesa_old_greek",
      name: "Old Greek House",
      zone: "Capadocia",
      hours: "12:00 a 22:30",
      howFar: "2 min caminando",
      style: "Guisados de cocción lenta y carnes tiernas.",
      reservation: "recomendado",
      website: "https://www.oldgreekhouse.com",
      query: "Old Greek House Goreme",
      lat: 38.6431,
      lng: 34.83,
    }),
    mesa({
      id: "mesa_metropolis",
      name: "Metropolis Roof Garden",
      zone: "Atenas",
      hours: "7:00 a 00:00",
      howFar: "Terraza del hotel",
      style:
        "Cocina mediterránea creativa y vista al Partenón.",
      reservation: "recomendado",
      website: "https://www.electrahotels.gr",
      query: "Metropolis Roof Garden Electra Palace Athens",
      lat: 37.9758,
      lng: 23.7354,
    }),
    mesa({
      id: "mesa_zillers",
      name: "The Zillers",
      zone: "Atenas",
      hours: "19:00 a 00:30",
      howFar: "3 min caminando",
      style: "1 estrella Michelin, cocina contemporánea de vanguardia.",
      reservation: "indispensable",
      reservationNote: "Antes de iniciar el viaje",
      website: "https://www.thezillersathens.com",
      query: "The Zillers Athens",
      lat: 37.975,
      lng: 23.734,
    }),
    mesa({
      id: "mesa_ergon",
      name: "Ergon House",
      zone: "Atenas",
      hours: "7:00 a 00:00",
      howFar: "1 min caminando",
      style:
        "Mercado gourmet: eliges ingredientes y los chefs los cocinan al momento.",
      reservation: "recomendado",
      website: "https://houses.ergonfoods.com",
      query: "Ergon House Athens",
      lat: 37.9765,
      lng: 23.7342,
    }),
    mesa({
      id: "mesa_linou",
      name: "Linou Sompasis",
      zone: "Atenas",
      hours: "13:00 a 1:00 · cerrado lunes",
      howFar: "8 min en taxi",
      style: "Cocina griega de granja a la mesa.",
      reservation: "recomendado",
      website: "https://www.linousompasis.gr",
      query: "Linou Sompasis Athens",
      lat: 37.972,
      lng: 23.727,
    }),
    mesa({
      id: "mesa_saita",
      name: "Saita",
      zone: "Atenas",
      hours:
        "Lunes a viernes 12:00 a 23:00 · sábado y domingo 12:00 a 00:00",
      howFar: "6 min caminando",
      style: "Taberna subterránea (koutoki), informal y casera.",
      reservation: "no_necesario",
      website: "https://www.taverna-saita.locallya.com",
      query: "Saita Taverna Athens",
      lat: 37.9728,
      lng: 23.7308,
    }),
    mesa({
      id: "mesa_karamanlidika",
      name: "Karamanlidika",
      zone: "Atenas",
      hours: "9:00 a 23:00 · cerrado domingo",
      howFar: "8 min en taxi",
      style:
        "Asia Menor, Capadocia y Grecia: embutidos, carnes al comino y quesos.",
      reservation: "recomendado",
      website: "https://www.karamanlidika.gr",
      query: "Karamanlidika Athens",
      lat: 37.9788,
      lng: 23.7235,
    }),
    mesa({
      id: "mesa_metsovo",
      name: "Metsovo 1350m",
      zone: "Meteora",
      hours: "13:00 a 23:30",
      howFar: "En el hotel",
      style:
        "Gastronomía contemporánea local, vinos Katogi Averoff.",
      reservation: "recomendado",
      website: "https://www.metsovo1350m.com",
      query: "Metsovo 1350m restaurant",
      lat: 39.7708,
      lng: 21.1839,
    }),
    mesa({
      id: "mesa_nicolas",
      name: "Rincón de Nicolás",
      zone: "Meteora",
      hours: "12:00 a 23:00",
      howFar: "18 min en taxi",
      style:
        "Cordero a fuego lento, metsovela y sopa de cabra, vistas a la montaña.",
      reservation: "no_necesario",
      query: "Rincon de Nicolas Metsovo",
      lat: 39.772,
      lng: 21.175,
    }),
    mesa({
      id: "mesa_lele",
      name: "Léle",
      zone: "Meteora",
      hours: "13:30 a 23:30 · cerrado miércoles",
      howFar: "20 min en taxi",
      style: "Fusión italo-local: pastas, pizzas y cortes.",
      reservation: "recomendado",
      query: "Lele Trattoria Metsovo",
      lat: 39.769,
      lng: 21.19,
    }),
    mesa({
      id: "mesa_salonika",
      name: "Salonika",
      zone: "Salónica",
      hours: "13:00 a 3:00",
      howFar: "En el hotel",
      style: "Cocina griega moderna y mediterránea.",
      reservation: "recomendado",
      website: "https://www.makedoniapalacehotel.com",
      query: "Salonika Restaurant Makedonia Palace",
      lat: 40.5965,
      lng: 22.948,
    }),
    mesa({
      id: "mesa_clochard",
      name: "Clochard",
      zone: "Salónica",
      hours: "13:00 a 00:00",
      howFar: "8 min en taxi",
      style: "Cocina urbana contemporánea griega y mediterránea.",
      reservation: "recomendado",
      website: "https://clochard.gr",
      query: "Clochard Thessaloniki",
      lat: 40.632,
      lng: 22.9415,
    }),
    mesa({
      id: "mesa_grada",
      name: "Grada Nuevo",
      zone: "Salónica",
      hours: "13:00 a 23:00",
      howFar: "6 min en taxi",
      style: "Alta cocina marina de autor.",
      reservation: "recomendado",
      website: "https://www.gradanuevo.gr",
      query: "Grada Nuevo Thessaloniki",
      lat: 40.621,
      lng: 22.951,
    }),
    mesa({
      id: "mesa_tsinari",
      name: "Tsinari",
      zone: "Salónica",
      hours: "13:00 a 00:00",
      howFar: "9 min en taxi",
      style: "Taberna tradicional con influencia de Asia Menor.",
      reservation: "no_necesario",
      query: "Tsinari Thessaloniki",
      lat: 40.6418,
      lng: 22.9545,
    }),
  ];
}
